name 'blacksquarelabs-sysctl'
maintainer 'John Coleman'
maintainer_email 'chef@blacksquarelabs.com'
license 'Apache 2.0'
description 'Installs/Configures blacksquarelabs-sysctl'
long_description 'Installs/Configures blacksquarelabs-sysctl'
version '0.1.0'
depends 'sysctl', '=0.8.0'
